
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkarbwfzxfxgtnefcout.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrYXJid2Z6eGZ4Z3RuZWZjb3V0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxODE1NjQsImV4cCI6MjA2Mjc1NzU2NH0.dpioSL8nOpDeSlyq3MFGPiOdw5Yumy4Eac4Aks2fpFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
